### ISSUE TITLE
Adjust sound(s) volume based on impact energy

### ISSUE THREAD

**Issue by sleddog** [sleddog/pool#50]
When the ball is potted (and soon when other sounds are added) it is set to a static value.  This ticket could introduce variable sound volume based on impact energy.  Faster collisions == louder

**Comment by medusalix** [comment]
I'd like to work on that.

Do you think we could just calculate the magnitude of the velocity vector

![Magnitude](https://latex.codecogs.com/gif.latex?m=\sqrt{x^2&space;&plus;&space;y^2})

and adjust the volume based on that value?

**Comment by mauzzr** [comment]
Apologies @Medusalix , forgot to comment here before I started working on it. I took exactly the approach you described, see #51

**Comment by sleddog** [comment]
@Medusalix i love this idea!  Can you submit a PR?

**Comment by medusalix** [comment]
@pwelby No problem, I'll just work on another issue then :smile:.

**Comment by mauzzr** [comment]
There's definitely more we could do here. For example the speed -> volume mapping assumes the maximum velocity is always going to be 100 (which probably isn't the case given #47). Maybe we could make the mapping non-linear so that volume increases faster when balls are moving slowly. Something like:

![](http://latex2png.com/output//latex_19cef0a2a984eb82461c7efe34f9a6ae.png)

**Comment by sleddog** [comment]
@pwelby i love the math!  wanna take a crack at integrating this?  We also need some ball collision sounds.

**Comment by mauzzr** [comment]
Sure, I'll put it in my next PR.
